### ISSUE TITLE
run square_test.py error

### ISSUE THREAD

**Issue by WakeWang1996** [pmh47/dirt#38]
When I ran square_test.py,  I met this error:
------------------------------------------------------------------------------------------------------------------------
WARNING: Logging before flag parsing goes to stderr.
W0729 11:32:12.363955 140544179722048 deprecation_wrapper.py:119] From /home/wang/exprience/octopus/dirt/tests/square_test.py:41: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-07-29 11:32:12.364831: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-07-29 11:32:12.386736: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-29 11:32:12.387074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
2019-07-29 11:32:12.387160: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2019-07-29 11:32:12.387228: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2019-07-29 11:32:12.387277: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2019-07-29 11:32:12.387330: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2019-07-29 11:32:12.387380: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2019-07-29 11:32:12.387429: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2019-07-29 11:32:12.389456: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-07-29 11:32:12.389468: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2019-07-29 11:32:12.389866: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-29 11:32:12.458633: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-29 11:32:12.458983: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558e44b92c30 executing computations on platform CUDA. Devices:
2019-07-29 11:32:12.458997: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2070, Compute Capability 7.5
2019-07-29 11:32:12.478012: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192000000 Hz
2019-07-29 11:32:12.478914: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558e4516e830 executing computations on platform Host. Devices:
2019-07-29 11:32:12.478943: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-29 11:32:12.479003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-29 11:32:12.479025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      
2019-07-29 11:32:12.497810: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
  File "/home/wang/exprience/octopus/dirt/tests/square_test.py", line 54, in <module>
    main()
  File "/home/wang/exprience/octopus/dirt/tests/square_test.py", line 45, in main
    dirt_pixels = get_dirt_pixels().eval()
  File "/home/wang/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 731, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/wang/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 5579, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/wang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/wang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/wang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Rasterise' used by node Rasterise (defined at <string>:89) with these attrs: [width=128, channels=1, height=128]
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'

	 [[Rasterise]]

Errors may have originated from an input operation.
Input Source operations connected to node Rasterise:
 Rasterise/strided_slice_3 (defined at /home/wang/.local/lib/python2.7/site-packages/dirt/rasterise_ops.py:51)
------------------------------------------------------------------------------------------------------------------------
@pmh47 Could you tell me what makes this error? Thank you!

**Comment by pmh47** [comment]
This is not an error with DIRT, but an error with your cuda / tensorflow setup -- tensorflow cannot find the cuda runtime library `libcudart.so.10.0`. I think probably you are using a tensorflow version that assumes cuda 10.0, on a system with cuda 10.1 installed.

**Comment by WakeWang1996** [comment]
I changed my system environment and it worked, thank you!
