### ISSUE TITLE
segmentation fault for square_test.py

### ISSUE THREAD

**Issue by vineethbabu** [pmh47/dirt#43]
hi, i have successfully built dirt with the cmake command  
**cmake ../csrc -DOpenGL_PREFERENCE=GLVND**

below is the ldd librastarise.so output gdb stack:
![librastarise](https://user-images.githubusercontent.com/22217572/64777307-86266b00-d577-11e9-8496-c652351a7c05.png)

GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
Starting program: /usr/bin/python tests/square_test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3ea6700 (LWP 4841)]
[New Thread 0x7ffff36a5700 (LWP 4842)]
[New Thread 0x7ffff0ea4700 (LWP 4843)]
[New Thread 0x7fffec6a3700 (LWP 4844)]
[New Thread 0x7fffe9ea2700 (LWP 4845)]
[New Thread 0x7fffe76a1700 (LWP 4846)]
[New Thread 0x7fffe4ea0700 (LWP 4847)]
[Thread 0x7fffe4ea0700 (LWP 4847) exited]
[Thread 0x7fffe76a1700 (LWP 4846) exited]
[Thread 0x7fffe9ea2700 (LWP 4845) exited]
[Thread 0x7fffec6a3700 (LWP 4844) exited]
[Thread 0x7ffff0ea4700 (LWP 4843) exited]
[Thread 0x7ffff36a5700 (LWP 4842) exited]
[Thread 0x7ffff3ea6700 (LWP 4841) exited]
WARNING:tensorflow:From tests/square_test.py:41: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

[New Thread 0x7fffe4ea0700 (LWP 4851)]
2019-09-12 15:50:00.782730: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
[New Thread 0x7fffe76a1700 (LWP 4852)]
2019-09-12 15:50:00.795398: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-12 15:50:00.795987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
2019-09-12 15:50:00.799918: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-09-12 15:50:00.808814: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-09-12 15:50:00.813297: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-09-12 15:50:00.816800: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-09-12 15:50:00.823417: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-09-12 15:50:00.828508: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-09-12 15:50:00.834386: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-09-12 15:50:00.834486: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-12 15:50:00.835360: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-12 15:50:00.836154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-12 15:50:00.836557: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[New Thread 0x7fffe9ea2700 (LWP 4853)]
[New Thread 0x7fffec6a3700 (LWP 4854)]
[New Thread 0x7fff94c90700 (LWP 4855)]
[New Thread 0x7fff83249700 (LWP 4856)]
[New Thread 0x7fff82a48700 (LWP 4857)]
[New Thread 0x7fff82247700 (LWP 4858)]
[New Thread 0x7fff81a46700 (LWP 4859)]
[New Thread 0x7fff81245700 (LWP 4860)]
[New Thread 0x7fff80a44700 (LWP 4861)]
[New Thread 0x7fff3d3c8700 (LWP 4862)]
[New Thread 0x7fff3cbc7700 (LWP 4863)]
[New Thread 0x7fff0ffff700 (LWP 4864)]
[New Thread 0x7fff0f7fe700 (LWP 4865)]
2019-09-12 15:50:00.904098: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-12 15:50:00.904740: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x416ad30 executing computations on platform CUDA. Devices:
2019-09-12 15:50:00.904771: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1070, Compute Capability 6.1
[Thread 0x7fff3d3c8700 (LWP 4862) exited]
[New Thread 0x7fff3d3c8700 (LWP 4866)]
[New Thread 0x7fff0effd700 (LWP 4867)]
[New Thread 0x7fff0e7fc700 (LWP 4868)]
2019-09-12 15:50:00.924626: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
[New Thread 0x7fff0effd700 (LWP 4869)]
[Thread 0x7fff0effd700 (LWP 4867) exited]
[New Thread 0x7fff0dffb700 (LWP 4870)]
[New Thread 0x7fff0d7fa700 (LWP 4871)]
[New Thread 0x7fff0cff9700 (LWP 4872)]
[New Thread 0x7fff05fff700 (LWP 4873)]
[New Thread 0x7fff057fe700 (LWP 4874)]
[New Thread 0x7fff04ffd700 (LWP 4875)]
[New Thread 0x7ffef9fff700 (LWP 4876)]
2019-09-12 15:50:00.925739: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x41dbdf0 executing computations on platform Host. Devices:
2019-09-12 15:50:00.925756: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
[New Thread 0x7ffef97fe700 (LWP 4877)]
2019-09-12 15:50:00.925922: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-12 15:50:00.926432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
2019-09-12 15:50:00.926461: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-09-12 15:50:00.926471: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-09-12 15:50:00.926481: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-09-12 15:50:00.926490: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-09-12 15:50:00.926499: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-09-12 15:50:00.926508: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-09-12 15:50:00.926516: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-09-12 15:50:00.926553: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-12 15:50:00.927056: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-12 15:50:00.927535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-12 15:50:00.927557: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-09-12 15:50:00.928306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-12 15:50:00.928318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-09-12 15:50:00.928324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-09-12 15:50:00.928431: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-12 15:50:00.928942: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-12 15:50:00.929440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7182 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
[New Thread 0x7ffef8ffd700 (LWP 4878)]
[New Thread 0x7ffecbfff700 (LWP 4879)]
[New Thread 0x7ffecb7fe700 (LWP 4880)]
[New Thread 0x7ffecaffd700 (LWP 4881)]
[New Thread 0x7ffeca7fc700 (LWP 4882)]
[New Thread 0x7ffec9ffb700 (LWP 4883)]
[New Thread 0x7ffec97fa700 (LWP 4884)]
[New Thread 0x7ffec8ff9700 (LWP 4885)]
[New Thread 0x7ffeb3fff700 (LWP 4886)]
[New Thread 0x7ffeb37fe700 (LWP 4887)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fff99042577 in tensorflow::Status tensorflow::shape_inference::InferenceContext::GetAttr<int>(absl::string_view, int*) const () from /home/drive/dirt/dirt/librasterise.so
#0  0x00007fff99042577 in tensorflow::Status tensorflow::shape_inference::InferenceContext::GetAttr<int>(absl::string_view, int*) const () from /home/drive/dirt/dirt/librasterise.so
#1  0x00007fff9903b8a6 in {lambda(tensorflow::shape_inference::InferenceContext*)#1}::operator()(tensorflow::shape_inference::InferenceContext*) const () from /home/drive/dirt/dirt/librasterise.so
#2  0x00007fff9903bb3e in {lambda(tensorflow::shape_inference::InferenceContext*)#1}::_FUN(tensorflow::shape_inference::InferenceContext*) () from /home/drive/dirt/dirt/librasterise.so
#3  0x00007fff99042c69 in std::_Function_handler<tensorflow::Status (tensorflow::shape_inference::InferenceContext*), tensorflow::Status (*)(tensorflow::shape_inference::InferenceContext*)>::_M_invoke(std::_Any_data const&, tensorflow::shape_inference::InferenceContext*&&) () from /home/drive/dirt/dirt/librasterise.so
#4  0x00007fffa64fda9d in tensorflow::shape_inference::InferenceContext::Run(std::function<tensorflow::Status (tensorflow::shape_inference::InferenceContext*)> const&) ()
   from /home/drive/.local/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so.1
#5  0x00007fffaf772350 in tensorflow::ShapeRefiner::RunShapeFn(tensorflow::Node const*, tensorflow::OpRegistrationData const*, tensorflow::ExtendedInferenceContext*) ()
   from /home/drive/.local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x00007fffaf773e78 in tensorflow::ShapeRefiner::AddNode(tensorflow::Node const*) () from /home/drive/.local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#7  0x00007fffac5c175a in TF_FinishOperation () from /home/drive/.local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#8  0x00007fffa9e34bd6 in _wrap_TF_FinishOperation () from /home/drive/.local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#9  0x00000000004bd1da in PyEval_EvalFrameEx ()
#10 0x00000000004ba916 in PyEval_EvalCodeEx ()
#11 0x00000000004c2c3c in PyEval_EvalFrameEx ()
#12 0x00000000004ba916 in PyEval_EvalCodeEx ()
#13 0x00000000004d6353 in ?? ()
#14 0x00000000004eec7e in ?? ()
#15 0x00000000004ee836 in ?? ()
#16 0x00000000004ab6fb in ?? ()
#17 0x00000000004c235d in PyEval_EvalFrameEx ()
#18 0x00000000004ba916 in PyEval_EvalCodeEx ()
#19 0x00000000004d6353 in ?? ()
#20 0x00000000004a63fe in PyObject_Call ()
#21 0x00000000004c35d8 in PyEval_EvalFrameEx ()
#22 0x00000000004ba916 in PyEval_EvalCodeEx ()
#23 0x00000000004c2c3c in PyEval_EvalFrameEx ()
#24 0x00000000004ba916 in PyEval_EvalCodeEx ()
#25 0x00000000004c24ea in PyEval_EvalFrameEx ()
#26 0x00000000004ba916 in PyEval_EvalCodeEx ()
#27 0x00000000004c24ea in PyEval_EvalFrameEx ()
#28 0x00000000004ba916 in PyEval_EvalCodeEx ()
#29 0x00000000004c24ea in PyEval_EvalFrameEx ()
#30 0x00000000004ba916 in PyEval_EvalCodeEx ()
#31 0x00000000004c24ea in PyEval_EvalFrameEx ()
#32 0x00000000004c210f in PyEval_EvalFrameEx ()
#33 0x00000000004c210f in PyEval_EvalFrameEx ()
#34 0x00000000004ba916 in PyEval_EvalCodeEx ()
#35 0x00000000004eb1bf in ?? ()
#36 0x00000000004e5e52 in PyRun_FileExFlags ()
#37 0x00000000004e4706 in PyRun_SimpleFileExFlags ()
#38 0x000000000049380e in Py_Main ()
#39 0x00007ffff7810830 in __libc_start_main (main=0x4932b0 <main>, argc=2, argv=0x7fffffffdd58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd48)
---Type <return> to continue, or q <return> to quit---q
 at ../csu/lQuit
A debugging session is active.

	Inferior 1 [process 4837] will be killed.

could you please check what went wrong in the installation?.

**Comment by vineethbabu** [comment]
We have a requirement to use Dirt as a dependency for another project that runs in Python2.7 only. 

To verify if Dirt works at all, I have used Python3.5, TF 1.14, and done the GLVND setting etc. But its giving Segmentation fault.

If I downgrade to TF 1.13.2, then I have an issue with libcublas.so. my machine has CUDA 10.1 and TF 1.13.2 expects a slighly older version of CUDA I think, so not sure if I have to downgrade CUDA also and retry the whole thing. 

Alternatively, if you can help me with the correct settings for Python2.7 on Ubuntu 16.04, it will be very helpful. which version of CUDA, TF are known to work correctly. I can just try that out. 

thanks in advance!!

**Comment by pmh47** [comment]
Are you using pip/conda packages of tensorflow, or building it from source? If using the official packages, then note that cuda 10.1 is not officially supported even by tf 1.14, so you should indeed downgrade -- cuda 10.0 should work with tf 1.13.x and tf 1.14.

As regards python 2.7 on Ubuntu 16.04, the following works:
- cuda 10.0
- libcudnn7 and libcudnn7-dev, both version 7.4.1.5 (available in ubuntu's package repo)
- tensorflow-gpu 1.13.2

**Comment by vineethbabu** [comment]
Thank you @pmh47  for your quick responses. I dowgraded cuda to 10.0 and tensorflow to 1.13.2 and it worked.
