### ISSUE TITLE
build error when run pip install .

### ISSUE THREAD

**Issue by zhangli-jerry** [pmh47/dirt#82]
I used aws [Deep Learning AMI (Ubuntu 16.04) Version 32.0 (ami-019034fd7c36a9148)].
I can not find out the reason from the following error message.

`  Building wheel for dirt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/anaconda3/envs/tensorflow_p27/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-EAVVa3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-EAVVa3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-f2xW7Z --python-tag cp27
       cwd: /tmp/pip-req-build-EAVVa3/
  Complete output (109 lines):
  running bdist_wheel
  running build
  -- The CXX compiler identification is GNU 5.4.0
  -- The CUDA compiler identification is NVIDIA 10.0.130
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
  -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
  -- Detecting CUDA compiler ABI info
  -- Detecting CUDA compiler ABI info - done
  -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components:  OpenGL EGL
  WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/__init__.py:1473: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.

  WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/__init__.py:1473: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.

  WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/__init__.py:1473: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.

  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-EAVVa3/build
  Scanning dependencies of target rasterise
  [ 14%] Building CXX object CMakeFiles/rasterise.dir/rasterise_egl.cpp.o
  [ 28%] Building CUDA object CMakeFiles/rasterise.dir/rasterise_egl.cu.o
  [ 42%] Building CXX object CMakeFiles/rasterise.dir/rasterise_grad_egl.cpp.o
  [ 57%] Building CUDA object CMakeFiles/rasterise.dir/rasterise_grad_egl.cu.o
  In file included from /tmp/pip-req-build-EAVVa3/csrc/rasterise_egl.cpp:24:0:
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceCuda.h:3:2: warning: #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file" [-Wcpp]
   #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file"
    ^
  In file included from /tmp/pip-req-build-EAVVa3/csrc/rasterise_grad_egl.cpp:22:0:
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceCuda.h:3:2: warning: #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file" [-Wcpp]
   #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file"
    ^
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/strings/string_view.h(495): warning: expression has no effect

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/strings/string_view.h(495): warning: expression has no effect

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/types/optional.h(425): warning: expression has no effect
            detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=stream_executor::dnn::AlgorithmDesc]"
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/tensorflow/stream_executor/dnn.h(802): here

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/types/optional.h(425): warning: expression has no effect
            detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=stream_executor::dnn::AlgorithmDesc]"
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/tensorflow/stream_executor/dnn.h(802): here

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/types/optional.h(425): warning: expression has no effect
            detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=size_t]"
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/tensorflow/stream_executor/dnn.h(856): here

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/types/optional.h(425): warning: expression has no effect
            detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=size_t]"
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/tensorflow/stream_executor/dnn.h(856): here

  make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libEGL.so', needed by 'CMakeFiles/rasterise.dir/cmake_device_link.o'.  Stop.
  make[2]: *** Waiting for unfinished jobs....
  [ 71%] Building CXX object CMakeFiles/rasterise.dir/shaders.cpp.o
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/strings/string_view.h(495): warning: expression has no effect

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/strings/string_view.h(495): warning: expression has no effect

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/types/optional.h(425): warning: expression has no effect
            detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=stream_executor::dnn::AlgorithmDesc]"
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/tensorflow/stream_executor/dnn.h(802): here

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/types/optional.h(425): warning: expression has no effect
            detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=size_t]"
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/tensorflow/stream_executor/dnn.h(856): here

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/types/optional.h(425): warning: expression has no effect
            detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=stream_executor::dnn::AlgorithmDesc]"
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/tensorflow/stream_executor/dnn.h(802): here

  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/absl/types/optional.h(425): warning: expression has no effect
            detected during instantiation of "const T &absl::optional<T>::operator*() const & [with T=size_t]"
  /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow_core/include/tensorflow/stream_executor/dnn.h(856): here

  CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/rasterise.dir/all' failed
  make[1]: *** [CMakeFiles/rasterise.dir/all] Error 2
  Makefile:83: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-EAVVa3/setup.py", line 50, in <module>
      'Programming Language :: Python :: 3.7',
    File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-EAVVa3/setup.py", line 24, in run
      build_csrc()
    File "/tmp/pip-req-build-EAVVa3/setup.py", line 20, in build_csrc
      subprocess.check_call(['make', '-j{}'.format(build_cpus)], cwd=build_path)
    File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for dirt
`

**Comment by zhangli-jerry** [comment]
I found out the problem:
` make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libEGL.so', needed by 'CMakeFiles/rasterise.dir/cmake_device_link.o'.  Stop.`

To fix the problem, I updated the symbolic link as follows:( Thanks @elect for the solution)
sudo rm /usr/lib/x86_64-linux-gnu/libEGL.so
sudo ln /usr/lib/x86_64-linux-gnu/libEGL.so.1 /usr/lib/x86_64-linux-gnu/libEGL.so
