### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by jiangolder** [pmh47/dirt#89]
My setting is Ubuntu16.04, cuda10.0, python3.6.12, tensorflow-gpu==1.15.0

when I was trying to use pip install . for installation, the errors are:
Defaulting to user installation because normal site-packages is not writeable
Processing /home/wanglab-robot/hand-imitation-learning/honnotate/dirt
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from dirt==0.3.0) (1.17.4)
Requirement already satisfied: tensorflow-gpu>=1.6 in /usr/lib/python3/dist-packages (from dirt==0.3.0) (2.3.1)
Building wheels for collected packages: dirt
  Building wheel for dirt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-d_sudtpa/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-d_sudtpa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hiuwgeb0
       cwd: /tmp/pip-req-build-d_sudtpa/
  Complete output (77 lines):
  running bdist_wheel
  running build
  -- The CXX compiler identification is GNU 7.5.0
  -- The CUDA compiler identification is NVIDIA 11.1.74
  -- Check for working CXX compiler: /usr/local/bin/g++
  -- Check for working CXX compiler: /usr/local/bin/g++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Check for working CUDA compiler: /usr/bin/nvcc
  -- Check for working CUDA compiler: /usr/bin/nvcc -- works
  -- Detecting CUDA compiler ABI info
  -- Detecting CUDA compiler ABI info - done
  -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components: OpenGL EGL
  2020-12-09 15:36:50.425886: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
  2020-12-09 15:36:50.504972: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
  Invalid MIT-MAGIC-COOKIE-1 key2020-12-09 15:36:52.873859: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
  2020-12-09 15:36:52.876610: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
  Invalid MIT-MAGIC-COOKIE-1 key2020-12-09 15:36:54.366776: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
  2020-12-09 15:36:54.369497: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
  Invalid MIT-MAGIC-COOKIE-1 key-- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-d_sudtpa/build
  Scanning dependencies of target rasterise
  [ 33%] Building CUDA object CMakeFiles/rasterise.dir/rasterise_egl.cu.o
  [ 33%] Building CUDA object CMakeFiles/rasterise.dir/rasterise_grad_egl.cu.o
  [ 66%] Building CXX object CMakeFiles/rasterise.dir/rasterise_grad_egl.cpp.o
  [ 66%] Building CXX object CMakeFiles/rasterise.dir/rasterise_egl.cpp.o
  nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
  make[2]: *** [CMakeFiles/rasterise.dir/build.make:76: CMakeFiles/rasterise.dir/rasterise_egl.cu.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
  make[2]: *** [CMakeFiles/rasterise.dir/build.make:102: CMakeFiles/rasterise.dir/rasterise_grad_egl.cu.o] Error 1
  In file included from /tmp/pip-req-build-d_sudtpa/csrc/rasterise_grad_egl.cpp:22:0:
  /usr/lib/python3/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceCuda.h:3:2: warning: #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file" [-Wcpp]
   #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file"
    ^~~~~~~
  In file included from /tmp/pip-req-build-d_sudtpa/csrc/rasterise_egl.cpp:24:0:
  /usr/lib/python3/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceCuda.h:3:2: warning: #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file" [-Wcpp]
   #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file"
    ^~~~~~~
  /tmp/pip-req-build-d_sudtpa/csrc/rasterise_grad_egl.cpp: In lambda function:
  /tmp/pip-req-build-d_sudtpa/csrc/rasterise_grad_egl.cpp:49:90: warning: ignoring return value of ‘tensorflow::Status tensorflow::shape_inference::InferenceContext::ReplaceDim(tensorflow::shape_inference::ShapeHandle, tensorflow::int64, tensorflow::shape_inference::DimensionHandle, tensorflow::shape_inference::ShapeHandle*)’, declared with attribute warn_unused_result [-Wunused-result]
           c->ReplaceDim(c->input(0), 2, c->Dim(c->input(2), 3), &grad_vertex_colours_shape);  // i.e. vertex-colors has same shape as vertices, but with final dimension replaced by channel count
                                                                                            ^
  In file included from /tmp/pip-req-build-d_sudtpa/csrc/rasterise_grad_egl.cpp:13:0:
  /usr/lib/python3/dist-packages/tensorflow/include/tensorflow/core/framework/shape_inference.h:418:10: note: declared here
     Status ReplaceDim(ShapeHandle s, int64 dim_index, DimensionHandle new_dim,
            ^~~~~~~~~~
  make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/rasterise.dir/all] Error 2
  make: *** [Makefile:84: all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-d_sudtpa/setup.py", line 27, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-d_sudtpa/setup.py", line 24, in run
      build_csrc()
    File "/tmp/pip-req-build-d_sudtpa/setup.py", line 20, in build_csrc
      subprocess.check_call(['make', '-j{}'.format(build_cpus)], cwd=build_path)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for dirt
  Running setup.py clean for dirt
Failed to build dirt
Installing collected packages: dirt
    Running setup.py install for dirt ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-d_sudtpa/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-d_sudtpa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uz8n7g16/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/wanglab-robot/.local/include/python3.8/dirt
         cwd: /tmp/pip-req-build-d_sudtpa/
    Complete output (48 lines):
    running install
    running build
    2020-12-09 15:36:59.704452: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
    2020-12-09 15:36:59.707960: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
    Invalid MIT-MAGIC-COOKIE-1 key2020-12-09 15:37:01.202660: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
    2020-12-09 15:37:01.205204: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
    Invalid MIT-MAGIC-COOKIE-1 key2020-12-09 15:37:02.669757: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
    2020-12-09 15:37:02.672508: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
    Invalid MIT-MAGIC-COOKIE-1 key-- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-req-build-d_sudtpa/build
    [ 16%] Building CUDA object CMakeFiles/rasterise.dir/rasterise_egl.cu.o
    [ 33%] Building CXX object CMakeFiles/rasterise.dir/shaders.cpp.o
    [ 50%] Building CUDA object CMakeFiles/rasterise.dir/rasterise_grad_egl.cu.o
    nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
    make[2]: *** [CMakeFiles/rasterise.dir/build.make:76: CMakeFiles/rasterise.dir/rasterise_egl.cu.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
    make[2]: *** [CMakeFiles/rasterise.dir/build.make:102: CMakeFiles/rasterise.dir/rasterise_grad_egl.cu.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/rasterise.dir/all] Error 2
    make: *** [Makefile:84: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-d_sudtpa/setup.py", line 27, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-d_sudtpa/setup.py", line 24, in run
        build_csrc()
      File "/tmp/pip-req-build-d_sudtpa/setup.py", line 20, in build_csrc
        subprocess.check_call(['make', '-j{}'.format(build_cpus)], cwd=build_path)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-d_sudtpa/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-d_sudtpa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uz8n7g16/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/wanglab-robot/.local/include/python3.8/dirt Check the logs for full command output.

When I install in the development mode, the error is:
cmake ../csrc
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.1.74
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components: OpenGL EGL 
2020-12-09 15:37:38.026647: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-09 15:37:38.029756: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Invalid MIT-MAGIC-COOKIE-1 key2020-12-09 15:37:39.524808: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-09 15:37:39.527481: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Invalid MIT-MAGIC-COOKIE-1 key2020-12-09 15:37:41.007646: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-09 15:37:41.010399: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Invalid MIT-MAGIC-COOKIE-1 key-- Configuring done
-- Generating done
-- Build files have been written to: /home/wanglab-robot/hand-imitation-learning/honnotate/dirt/build
wanglab-robot@lambda-dual:~/hand-imitation-learning/honnotate/dirt/build$ make
Scanning dependencies of target rasterise
[ 16%] Building CXX object CMakeFiles/rasterise.dir/rasterise_egl.cpp.o
In file included from /home/wanglab-robot/hand-imitation-learning/honnotate/dirt/csrc/rasterise_egl.cpp:24:0:
/usr/lib/python3/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceCuda.h:3:2: warning: #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file" [-Wcpp]
 #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file"
  ^~~~~~~
[ 33%] Building CUDA object CMakeFiles/rasterise.dir/rasterise_egl.cu.o
nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
make[2]: *** [CMakeFiles/rasterise.dir/build.make:76: CMakeFiles/rasterise.dir/rasterise_egl.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/rasterise.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by pmh47** [comment]
The error is because cuda 11 no longer supports sm30 as target architecture. I think you can fix easily, by changing `sm_30` to `sm_60` in `dirt/csrc/CMakeLists.txt` line 41. Note I have not yet tested on cuda 11, so it's possible you'll see other problems!

**Comment by jiangolder** [comment]
> The error is because cuda 11 no longer supports sm30 as target architecture. I think you can fix easily, by changing `sm_30` to `sm_60` in `dirt/csrc/CMakeLists.txt` line 41. Note I have not yet tested on cuda 11, so it's possible you'll see other problems!

Thank you! This works. But currently I encountered another problem.

2020-12-09 18:44:45.561461: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-09 18:44:45.563857: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Invalid MIT-MAGIC-COOKIE-1 key2020-12-09 18:44:47.817618: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-09 18:44:47.820354: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Invalid MIT-MAGIC-COOKIE-1 key2020-12-09 18:44:49.385170: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-09 18:44:49.387833: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Invalid MIT-MAGIC-COOKIE-1 key-- Configuring done
-- Generating done
-- Build files have been written to: /home/wanglab-robot/hand-imitation-learning/honnotate/dirt/build
[ 16%] Building CXX object CMakeFiles/rasterise.dir/rasterise_egl.cpp.o
In file included from /home/wanglab-robot/hand-imitation-learning/honnotate/dirt/csrc/rasterise_egl.cpp:24:0:
/usr/lib/python3/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceCuda.h:3:2: warning: #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file" [-Wcpp]
 #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file"
  ^~~~~~~
[ 33%] Building CUDA object CMakeFiles/rasterise.dir/rasterise_egl.cu.o
/usr/include/c++/9/utility(310): error: pack expansion does not make use of any argument packs

/usr/lib/python3/dist-packages/tensorflow/include/tensorflow/core/platform/env.h(368): warning: overloaded virtual function "tensorflow::Env::RegisterFileSystem" is only partially overridden in class "tensorflow::EnvWrapper"

/usr/lib/python3/dist-packages/tensorflow/include/absl/types/optional.h(428): warning: expression has no effect
          detected during instantiation of "const T &absl::lts_2020_02_25::optional<T>::operator*() const & [with T=stream_executor::dnn::AlgorithmDesc]" 
/usr/lib/python3/dist-packages/tensorflow/include/tensorflow/stream_executor/dnn.h(804): here

/usr/lib/python3/dist-packages/tensorflow/include/absl/types/optional.h(428): warning: expression has no effect
          detected during:
            instantiation of "const T &absl::lts_2020_02_25::optional<T>::operator*() const & [with T=size_t]" 
(605): here
            instantiation of "auto absl::lts_2020_02_25::operator==(const absl::lts_2020_02_25::optional<T> &, const absl::lts_2020_02_25::optional<U> &)->__nv_bool [with T=size_t, U=size_t]" 
/usr/lib/python3/dist-packages/tensorflow/include/tensorflow/stream_executor/dnn.h(858): here

/usr/include/c++/9/utility(310): error: identifier "__integer_pack" is undefined
          detected during:
            instantiation of class "std::_Build_index_tuple<_Num> [with _Num=1UL]" 
/usr/include/c++/9/thread(250): here
            instantiation of "std::thread::_Invoker<_Tuple>::__result<_Tuple>::type std::thread::_Invoker<_Tuple>::operator()() [with _Tuple=std::tuple<std::function<void ()>>]" 
/usr/include/c++/9/thread(195): here
            instantiation of "void std::thread::_State_impl<_Callable>::_M_run() [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(192): here
            implicit generation of "std::thread::_State_impl<_Callable>::~_State_impl() [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(192): here
            instantiation of class "std::thread::_State_impl<_Callable> [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(192): here
            instantiation of "std::thread::_State_impl<_Callable>::_State_impl(_Callable &&) [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(206): here
            instantiation of "std::thread::_State_ptr std::thread::_S_make_state(_Callable &&) [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(132): here
            instantiation of "std::thread::thread(_Callable &&, _Args &&...) [with _Callable=std::function<void ()>, _Args=<>, <unnamed>=void]" 
/usr/lib/python3/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/ThreadPool/ThreadEnvironment.h(24): here

/usr/include/c++/9/utility(310): error: expected a ">"
          detected during:
            instantiation of class "std::_Build_index_tuple<_Num> [with _Num=1UL]" 
/usr/include/c++/9/thread(250): here
            instantiation of "std::thread::_Invoker<_Tuple>::__result<_Tuple>::type std::thread::_Invoker<_Tuple>::operator()() [with _Tuple=std::tuple<std::function<void ()>>]" 
/usr/include/c++/9/thread(195): here
            instantiation of "void std::thread::_State_impl<_Callable>::_M_run() [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(192): here
            implicit generation of "std::thread::_State_impl<_Callable>::~_State_impl() [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(192): here
            instantiation of class "std::thread::_State_impl<_Callable> [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(192): here
            instantiation of "std::thread::_State_impl<_Callable>::_State_impl(_Callable &&) [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(206): here
            instantiation of "std::thread::_State_ptr std::thread::_S_make_state(_Callable &&) [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
/usr/include/c++/9/thread(132): here
            instantiation of "std::thread::thread(_Callable &&, _Args &&...) [with _Callable=std::function<void ()>, _Args=<>, <unnamed>=void]" 
/usr/lib/python3/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/ThreadPool/ThreadEnvironment.h(24): here

/usr/include/c++/9/thread(251): error: no instance of function template "std::thread::_Invoker<_Tuple>::_M_invoke [with _Tuple=std::tuple<std::function<void ()>>]" matches the argument list
            argument types are: (<error-type>)
          detected during:
            instantiation of "std::thread::_Invoker<_Tuple>::__result<_Tuple>::type std::thread::_Invoker<_Tuple>::operator()() [with _Tuple=std::tuple<std::function<void ()>>]" 
(195): here
            instantiation of "void std::thread::_State_impl<_Callable>::_M_run() [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
(192): here
            implicit generation of "std::thread::_State_impl<_Callable>::~_State_impl() [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
(192): here
            instantiation of class "std::thread::_State_impl<_Callable> [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
(192): here
            instantiation of "std::thread::_State_impl<_Callable>::_State_impl(_Callable &&) [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
(206): here
            instantiation of "std::thread::_State_ptr std::thread::_S_make_state(_Callable &&) [with _Callable=std::thread::_Invoker<std::tuple<std::function<void ()>>>]" 
(132): here
            instantiation of "std::thread::thread(_Callable &&, _Args &&...) [with _Callable=std::function<void ()>, _Args=<>, <unnamed>=void]" 
/usr/lib/python3/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/ThreadPool/ThreadEnvironment.h(24): here

4 errors detected in the compilation of "/home/wanglab-robot/hand-imitation-learning/honnotate/dirt/csrc/rasterise_egl.cu".
make[2]: *** [CMakeFiles/rasterise.dir/build.make:76: CMakeFiles/rasterise.dir/rasterise_egl.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/rasterise.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
