### ISSUE TITLE
Error while pip install . 

### ISSUE THREAD

**Issue by Vikas-Sony** [pmh47/dirt#98]
I checked a similar issue that was posted on this repo, wherein the error occurred due to the missing `libOpenGL.so` file. But in this case, OpenGL and the necessary requirements were found.

`
ERROR: Command errored out with exit status 1:
   command: /home/ingnious/.pyenv/versions/3.6.13/envs/tflow/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-83ecgkg8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-83ecgkg8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-x5yn9tds
       cwd: /tmp/pip-req-build-83ecgkg8/
  Complete output (132 lines):
  running bdist_wheel
  running build
  -- The CXX compiler identification is GNU 9.3.0
  -- The CUDA compiler identification is NVIDIA 10.1.243
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Check for working CUDA compiler: /usr/bin/nvcc
  -- Check for working CUDA compiler: /usr/bin/nvcc -- works
  -- Detecting CUDA compiler ABI info
  -- Detecting CUDA compiler ABI info - done
  -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components: OpenGL EGL
  Traceback (most recent call last):
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
      from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
      from tensorflow.python import pywrap_tensorflow
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
      raise ImportError(msg)
  ImportError: Traceback (most recent call last):
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
  
  
  Failed to load the native TensorFlow runtime.
  
  See https://www.tensorflow.org/install/errors
  
  for some common reasons and solutions.  Include the entire stack trace
  above this error message when asking for help.
  Traceback (most recent call last):
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
      from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
      from tensorflow.python import pywrap_tensorflow
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
      raise ImportError(msg)
  ImportError: Traceback (most recent call last):
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
  
  
  Failed to load the native TensorFlow runtime.
  
  See https://www.tensorflow.org/install/errors
  
  for some common reasons and solutions.  Include the entire stack trace
  above this error message when asking for help.
  CMake Error at CMakeLists.txt:26 (message):
    cannot find either cuda_launch_config.h or gpu_launch_config.h
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-83ecgkg8/build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-83ecgkg8/setup.py", line 50, in <module>
      'Programming Language :: Python :: 3.7',
    File "/home/ingnious/.pyenv/versions/3.6.13/envs/tflow/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/ingnious/.pyenv/versions/3.6.13/envs/tflow/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-83ecgkg8/setup.py", line 24, in run
      build_csrc()
    File "/tmp/pip-req-build-83ecgkg8/setup.py", line 18, in build_csrc
      subprocess.check_call(['cmake', os.path.join(base_path, 'csrc')], cwd=build_path)
    File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-83ecgkg8/csrc']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dirt
  Running setup.py clean for dirt
Failed to build dirt
Installing collected packages: dirt
    Running setup.py install for dirt ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ingnious/.pyenv/versions/3.6.13/envs/tflow/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-83ecgkg8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-83ecgkg8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g9p9bxna/install-record.txt --single-version-externally-managed --compile --install-headers /home/ingnious/.pyenv/versions/3.6.13/envs/tflow/include/site/python3.6/dirt
         cwd: /tmp/pip-req-build-83ecgkg8/
    Complete output (121 lines):
    running install
    running build
    Traceback (most recent call last):
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
    
    
    Failed to load the native TensorFlow runtime.
    
    See https://www.tensorflow.org/install/errors
    
    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.
    Traceback (most recent call last):
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/home/ingnious/.pyenv/versions/tflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
    
    
    Failed to load the native TensorFlow runtime.
    
    See https://www.tensorflow.org/install/errors
    
    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.
    CMake Error at CMakeLists.txt:26 (message):
      cannot find either cuda_launch_config.h or gpu_launch_config.h
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-83ecgkg8/build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-83ecgkg8/setup.py", line 50, in <module>
        'Programming Language :: Python :: 3.7',
      File "/home/ingnious/.pyenv/versions/3.6.13/envs/tflow/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ingnious/.pyenv/versions/3.6.13/envs/tflow/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-83ecgkg8/setup.py", line 24, in run
        build_csrc()
      File "/tmp/pip-req-build-83ecgkg8/setup.py", line 18, in build_csrc
        subprocess.check_call(['cmake', os.path.join(base_path, 'csrc')], cwd=build_path)
      File "/home/ingnious/.pyenv/versions/3.6.13/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-83ecgkg8/csrc']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ingnious/.pyenv/versions/3.6.13/envs/tflow/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-83ecgkg8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-83ecgkg8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g9p9bxna/install-record.txt --single-version-externally-managed --compile --install-headers /home/ingnious/.pyenv/versions/3.6.13/envs/tflow/include/site/python3.6/dirt Check the logs for full command output.

`

**Comment by pmh47** [comment]
This is a problem with tensorflow-gpu not loading the cuda libraries, not a problem with DIRT install itself. Does tensorflow definitely work correctly, in gpu mode, in this venv? You should follow the links suggested in the error message to fix. I'll close for now as it's not a DIRT issue.
